
version: 2

models:
  - name: transactions
    description: "Transactions event table"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

