swile:
  outputs:
    dev:
      dbname: swile

#      host: postgres-container
#      pass: password
      host: localhost
      pass: toor

      port: 5432
      schema: general
      threads: 1
      type: postgres
      user: postgres
  target: dev
